server:
  port: 8080

spring:
  application:
    name: bff-gateway

  main:
    web-application-type: reactive

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      routes:
        - id: usuario-service
          uri: http://usuario-service:8081
          predicates:
            - Path=/usuarios,/usuarios/**

        - id: establecimiento-service
          uri: http://establecimiento-service:8082
          predicates:
            - Path=/establecimiento,/establecimiento/**

        - id: asistencia-service
          uri: http://asistencia-service:8083
          predicates:
            - Path=/asistencia,/asistencia/**

        - id: academico-service
          uri: http://academico-service:8084
          predicates:
            - Path=/evaluacion,/evaluacion/**,/notas,/notas/**

microservicios:
  usuario-url: http://usuario-service:8081
  establecimiento-url: http://establecimiento-service:8082

resilience4j:
  circuitbreaker:
    instances:
      usuario-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true

      establecimiento-service:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,circuitbreakers

jwt:
  secret: ${JWT_SECRET:colegio-bernardo-ohiggins-secret-key-2026}