server:
  port: 8080

spring:
  application:
    name: bff-gateway
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: usuario-service
              uri: http://usuario-service:8081
              predicates:
                - Path=/usuarios,/usuarios/**
            - id: establecimiento-service
              uri: http://establecimiento-service:8082
              predicates:
                - Path=/establecimientos,/establecimientos/**
            - id: asistencia-service
              uri: http://asistencia-service:8083
              predicates:
                - Path=/asistencias,/asistencias/**

microservicios:
  usuario-url: http://usuario-service:8081
  establecimiento-url: http://establecimiento-service:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
